---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: django-postgres-password
  namespace: django-app
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: django-app-secret-store
    kind: SecretStore
  target:
    name: postgres-password
  data:
    - secretKey: password
      remoteRef:
        key: $POSTGRES_PASSWORD_SECRET_ID
        property: password
