apiVersion: batch/v1
kind: Job
metadata:
  name: migrations
  labels:
    app.kubernetes.io/name: demo
    app.kubernetes.io/component: migrations
spec:
  ttlSecondsAfterFinished: 100
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          image: $REPO_URL/app:v1
          imagePullPolicy: IfNotPresent
          command:
            - python
            - manage.py
            - migrate
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: DB_USER
              value: django
            - name: DB_NAME
              value: django
            - name: DB_HOST
              value: $POSTGRES_HOST
            - name: DB_PORT
              value: "6432"