---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: django-app-secret-store
  namespace: django-app
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yc-auth
          key: authorized-key
